name: Deploy Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy live to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages           # target branch
          folder: live               # folder to deploy
          clean: true                # remove old files
          token: ${{ secrets.GITHUB_TOKEN }}